[package]
name = "cw-orch"
version = "0.13.3"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Scripting library for deploying and interacting with CosmWasm smart-contracts"
keywords = ["cosmwasm", "blockchain"]
categories = ["development-tools"]
readme = "../README.md"

exclude = [".env"]

[package.metadata.docs.rs]
# passes all-features to cargo when building the docs.
all-features = true

[[example]]
name = "mock_test"

[[example]]
name = "daemon_test"
required-features = ["daemon"]

[[example]]
name = "osmosis_test_tube"
required-features = ["osmosis-test-tube"]

[[example]]
name = "injective"
required-features = ["eth"]

[[example]]
name = "bank_query"
path = "examples/queries/bank_query.rs"
require-features = ["daemon"]

[features]
default = []
# enable node-backed tests (ensure Docker is running)
# run with `cargo test --jobs 1 --features node-tests`
node-tests = ["daemon"]
# enable the optional dependencies
daemon = [
  "dep:ibc-chain-registry",
  "dep:ibc-relayer-types",
  "dep:tokio",
  "dep:tonic",
  "dep:secp256k1",
  "dep:reqwest",
  "dep:base64",
  "dep:hkd32",
  "dep:rand_core",
  "dep:ed25519-dalek",
  "dep:cosmrs",
  "dep:derive_builder",
  "dep:eyre",
  "dep:chrono",
  "dep:base16",
  "dep:ripemd",
  "dep:ring",
  "dep:hex",
  "dep:bitcoin",
  "dep:prost",
]
eth = ["daemon", "dep:ethers-signers", "dep:ethers-core", "dep:snailquote"]
osmosis-test-tube = ["dep:osmosis-test-tube"]

[dependencies]
# Default deps
cw-orch-contract-derive = { path = "../packages/cw-orch-contract-derive", version = "0.13.3" }
cw-orch-fns-derive = { path = "../packages/cw-orch-fns-derive", version = "0.13.3" }

cosmwasm-std = { workspace = true }
cw-utils = { workspace = true }
cw-multi-test = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
schemars = "0.8.10"
log = "0.4.14"
serde_json = "1.0.79"
thiserror = { version = "1.0.21" }

# Daemon deps
sha256 = { version = "1.1.1" }
prost = { version = "0.11", optional = true }
bitcoin = { version = "0.30.0", optional = true }
hex = { version = "0.4.3", optional = true }
ripemd = { version = "0.1.3", optional = true }
ibc-chain-registry = { version = "0.24.1", optional = true }
ibc-relayer-types = { version = "0.24.1", optional = true }
tokio = { version = "1.4", features = ["full"], optional = true }
tonic = { version = "0.9.2", optional = true, features = ["tls", "tls-roots"] }
secp256k1 = { version = "0.27.0", default-features = false, optional = true }
reqwest = { version = "0.11.9", optional = true }
base64 = { version = "0.21.0", optional = true }
hkd32 = { version = "0.7.0", features = [
  "bip39",
  "mnemonic",
  "bech32",
], optional = true }
rand_core = { version = "0.6.4", default-features = false, optional = true }
ed25519-dalek = { version = "1", features = ["serde"], optional = true }
eyre = { version = "0.6", optional = true }
cosmrs = { version = "0.14.0", features = [
  "dev",
  "cosmwasm",
  "grpc",
], optional = true }
chrono = { version = "0.4", optional = true }
base16 = { version = "0.2.1", optional = true }
derive_builder = { version = "0.12.0", optional = true }
ring = { version = "0.16.20", optional = true }
flate2 = { version = "1.0.26" }

# Ethereum deps
ethers-signers = { version = "2.0.7", optional = true }
ethers-core = { version = "2.0.7", optional = true }
snailquote = { version = "0.3.1", optional = true }

# Test Tube env deps
osmosis-test-tube = { version = "16.0.0", optional = true }

[dev-dependencies]
cw-orch = { features = ["daemon"], path = "." }
uid = "0.1.7"
env_logger = "0.10.0"
cw20 = { git = "https://github.com/AbstractSDK/cw-plus.git" }
cw20-base = { git = "https://github.com/AbstractSDK/cw-plus.git" }
cosmwasm-schema = "1.2"
tokio-test = "0.4.2"
speculoos = "0.11.0"
ctor = "0.2.0"
duct = "0.13"
counter-contract = { path = "../contracts/counter", features = ["interface"] }
mock-contract = { path = "../contracts/mock_contract", features = [
  "interface",
] }
mock-contract-u64 = { path = "../contracts/mock_contract_u64", features = [
  "interface",
] }
serial_test = "2.0.0"

# Ethereum deps
ethers-signers = { version = "2.0.7" }
ethers-core = { version = "2.0.7" }
